{
 "title": "Energy dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "night_start", "query": "${VAR_NIGHT_START}" },
   { "name": "night_end", "query": "${VAR_NIGHT_END}" },
   { "name": "night_rate", "query": "${VAR_NIGHT_RATE}" },
   { "name": "day_rate", "query": "${VAR_DAY_RATE}" }
  ]
 },
 "panels": [
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "select (start_ts - (((start_ts * 1000) % $__interval_ms) / 1000.0)) as time, CONCAT(name,' Avg') as metric, AVG(mean * scale) as value from statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id\nwhere  start_ts >= ${__from:date:seconds} AND start_ts < ${__to:date:seconds} and name like '%Power%'\nGROUP BY time, metric\nORDER BY time"
    },
    {
     "rawSql": "select (start_ts - (((start_ts * 1000) % $__interval_ms) / 1000.0)) as time, CONCAT(name,' Min') as metric, MIN(min * scale) as value from statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id\nwhere  start_ts >= ${__from:date:seconds} AND start_ts < ${__to:date:seconds} and name like '%Power%' \nGROUP BY time, metric\nORDER BY time"
    },
    {
     "rawSql": "select (start_ts - (((start_ts * 1000) % $__interval_ms) / 1000.0)) as time, CONCAT(name,' Max') as metric, MAX(max * scale) as value from statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id\nwhere  start_ts >= ${__from:date:seconds} AND start_ts < ${__to:date:seconds} and name like '%Power%'\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  },
  {
   "title": "Power Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "select (start_ts - (((start_ts * 1000) % $__interval_ms) / 1000.0)) as time,\n       AVG(COALESCE(state, max)) as import\nfrom statistics_short_term\njoin statistics_meta on statistics_meta.id = statistics_short_term.metadata_id\nwhere start_ts >= ${__from:date:seconds} AND\n      start_ts < ${__to:date:seconds} AND\n      statistic_id = 'sensor.home_total'\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "select (start_ts - (((start_ts * 1000) % $__interval_ms) / 1000.0)) as time,\n       AVG(state) as total\nfrom statistics_short_term\njoin statistics_meta on statistics_meta.id = statistics_short_term.metadata_id\nwhere start_ts >= ${__from:date:seconds} AND \n      start_ts < ${__to:date:seconds} AND\n      statistic_id = 'sensor.home_kwh'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Power Pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "Select (MAX(start_ts)) AS time, joe_name_links.name AS metric, MAX(state) - MIN(state) from statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND\nname not like '%Home%' AND name like '%Total%'\nwhere start_ts >= ${__from:date:seconds} AND start_ts < ${__to:date:seconds}\nGROUP BY joe_name_links.metadata_id"
    },
    {
     "rawSql": "SELECT ${__to:date:seconds} AS time, (SUM(home_delta) - SUM(home_non_delta)) AS 'Home Misc' FROM\n(\n    Select IF (joe_name_links.name = 'Home Total', 0, MAX(state) - MIN(state)) AS home_non_delta,\n           IF (joe_name_links.name = 'Home Total', MAX(state) - MIN(state), 0) AS home_delta\n    from statistics_short_term\n    join joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND\n    name like '%Total%'\n    where start_ts >= ${__from:date:seconds} AND start_ts < ${__to:date:seconds}\n    GROUP BY joe_name_links.metadata_id\n) AS t"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n(start_ts - (((start_ts * 1000) % $__interval_ms) / 1000.0)) as time,\nSUM(delta)\nFROM\n(\nSELECT\nstart_ts,\nstate - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts) AS delta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name = 'Home Total'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n(start_ts - (((start_ts * 1000) % $__interval_ms) / 1000.0)) as time,\nSUM(delta * rate)\nFROM\n(\nSELECT\nstart_ts,\nTIME(FROM_UNIXTIME(start_ts)) AS time_of_day,\nstate - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts) AS delta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name = 'Home Total'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nJOIN joe_rate_links ON t.time_of_day BETWEEN joe_rate_links.start_time AND joe_rate_links.end_time AND\n\nt.start_ts BETWEEN joe_rate_links.valid_from_ts AND joe_rate_links.valid_to_ts\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "In Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nMAX(start_ts) AS time,\njoe_rate_links.name AS metric,\nSUM(delta) AS value\nFROM\n(\nSELECT\nstart_ts,\nTIME(FROM_UNIXTIME(start_ts)) AS time_of_day,\nstate - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts) AS delta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name = 'Home Total'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nJOIN joe_rate_links ON t.time_of_day BETWEEN joe_rate_links.start_time AND joe_rate_links.end_time AND\nt.start_ts BETWEEN joe_rate_links.valid_from_ts AND  joe_rate_links.valid_to_ts\nGROUP BY metric"
    }
   ]
  },
  {
   "title": "In Rate Cost",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nMAX(start_ts) AS time,\njoe_rate_links.name AS metric,\nSUM(delta * rate) AS value\nFROM\n(\nSELECT\nstart_ts,\nTIME(FROM_UNIXTIME(start_ts)) AS time_of_day,\nstate - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts) AS delta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name = 'Home Total'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nJOIN joe_rate_links ON t.time_of_day BETWEEN joe_rate_links.start_time AND joe_rate_links.end_time AND\nt.start_ts BETWEEN joe_rate_links.valid_from_ts AND  joe_rate_links.valid_to_ts\nGROUP BY metric"
    }
   ]
  },
  {
   "title": "In Rate Detailed",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nMAX(start_ts) AS time, \nCONCAT(joe_rate_links.name, ' - ', t.name) AS metric,\nSUM(delta) AS value\nFROM\n(\nSELECT\nstart_ts,\nTIME(FROM_UNIXTIME(start_ts)) AS time_of_day,\njoe_name_links.name,\nstate - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts) AS \ndelta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name like '%Total' AND name NOT LIKE 'Home%'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nJOIN joe_rate_links ON t.time_of_day BETWEEN joe_rate_links.start_time AND joe_rate_links.end_time AND\nt.start_ts BETWEEN joe_rate_links.valid_from_ts AND  joe_rate_links.valid_to_ts\nGROUP BY metric\nORDER BY time"
    },
    {
     "rawSql": "SELECT\nMAX(start_ts) AS time,\nSUM(home_delta) - SUM(known_delta) AS value,\nCONCAT(joe_rate_links.name, ' - Home Misc') AS metric\nFROM\n(\nSELECT\nstart_ts,\nTIME(FROM_UNIXTIME(start_ts)) AS time_of_day,\nIF (joe_name_links.name LIKE '%Home%', state - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts), 0) AS home_delta,\nIF (joe_name_links.name NOT LIKE '%Home%', state - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts), 0) AS known_delta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name like '%Total'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nJOIN joe_rate_links ON t.time_of_day BETWEEN joe_rate_links.start_time AND joe_rate_links.end_time AND\nt.start_ts BETWEEN joe_rate_links.valid_from_ts AND  joe_rate_links.valid_to_ts\nGROUP BY metric\nORDER BY time "
    }
   ]
  },
  {
   "title": "In Rate Cost Detailed",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nMAX(start_ts) AS time, \nCONCAT(joe_rate_links.name, ' - ', t.name) AS metric,\nSUM(delta * rate) AS value\nFROM\n(\nSELECT\nstart_ts,\nTIME(FROM_UNIXTIME(start_ts)) AS time_of_day,\njoe_name_links.name,\nstate - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts) AS \ndelta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name like '%Total' AND name NOT LIKE 'Home%'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nJOIN joe_rate_links ON t.time_of_day BETWEEN joe_rate_links.start_time AND joe_rate_links.end_time AND\nt.start_ts BETWEEN joe_rate_links.valid_from_ts AND  joe_rate_links.valid_to_ts\nGROUP BY metric\nORDER BY time"
    },
    {
     "rawSql": "SELECT\nMAX(start_ts) AS time,\nSUM(home_delta * rate) - SUM(known_delta * rate) AS value,\nCONCAT(joe_rate_links.name, ' - Home Misc') AS metric\nFROM\n(\nSELECT\nstart_ts,\nTIME(FROM_UNIXTIME(start_ts)) AS time_of_day,\nIF (joe_name_links.name LIKE '%Home%', state - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts), 0) AS home_delta,\nIF (joe_name_links.name NOT LIKE '%Home%', state - LAG(state, 1) OVER (PARTITION BY name ORDER BY start_ts), 0) AS known_delta\nfrom statistics_short_term\njoin joe_name_links on joe_name_links.metadata_id = statistics_short_term.metadata_id AND name like '%Total'\nwhere start_ts BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n) t\nJOIN joe_rate_links ON t.time_of_day BETWEEN joe_rate_links.start_time AND joe_rate_links.end_time AND\nt.start_ts BETWEEN joe_rate_links.valid_from_ts AND  joe_rate_links.valid_to_ts\nGROUP BY metric\nORDER BY time"
    }
   ]
  }
 ]
}